[package]
name = "devhub"
version = "0.0.1.0"
edition = "2024.beta" 

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
tale = "0x0"
talesmarket = "0x0"
talestransferpolicy = "0x0"
talesrules = "0x0"

[dev-dependencies]

[dev-addresses]
